### ISSUE TITLE
index2.htl will not work.

### ISSUE THREAD

**Issue by Svein-Tore** [katanaml/sample-apps#3]
Hi!

I have downloaded the index2.html file from your github.  But when  I run it  I get a lot of errors in the console.  Any suggestions?

I got the followinfg error (in console):    Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'setAttribute')
    at PyScript.evaluate (base.ts:128:79)

Error in py-script:

JsException(PythonError: Traceback (most recent call last): File "/lib/python3.10/asyncio/futures.py", line 201, in result raise self._exception File "/lib/python3.10/asyncio/tasks.py", line 232, in __step result = coro.send(None) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async await CodeRunner( File "/lib/python3.10/site-packages/_pyodide/_base.py", line 237, in __init__ self.ast = next(self._gen) File "/lib/python3.10/site-packages/_pyodide/_base.py", line 141, in _parse_and_compile_gen mod = compile(source, filename, mode, flags | ast.PyCF_ONLY_AST) File "", line 14 if file_input.value is not None: ^^ IndentationError: expected an indented block after function definition on line 13 )

**Comment by Svein-Tore** [comment]
I got it work. Was some problems with intendation.
